// projects/ui-grid-react/src/UiGrid.tsx
import React from 'react';
import type {
  GridOptions,
  GridCellTemplateContext,
  GridExpandableTemplateContext,
  UiGridApi,
  GridColumnDef,
  GridRow,
} from '@ornery/ui-grid';
import type { DisplayItem, RowItem } from '@ornery/ui-grid';
import { useGridState } from './useGridState';
import { useVirtualScroll } from './useVirtualScroll';

export interface UiGridProps {
  options: GridOptions;
  onRegisterApi?: (api: UiGridApi) => void;
  cellRenderer?: (context: GridCellTemplateContext) => React.ReactNode;
  expandableRenderer?: (context: GridExpandableTemplateContext) => React.ReactNode;
  className?: string;
}

export function UiGrid({
  options,
  onRegisterApi,
  cellRenderer,
  expandableRenderer,
  className,
}: UiGridProps) {
  const state = useGridState(options, onRegisterApi);

  const {
    pipeline,
    visibleColumns,
    labels,
    gridTemplateColumns,
    gridContainerRef,
    displayItems,
    virtualizationEnabled,
    pipelineMs,
    visibleRowCount,
    totalRows,
    benchmarkResult,
    rowSize,
    viewportHeightPx,
    editingValue,
    sortingFeature,
    filteringFeature,
    groupingFeature,
    paginationFeature,
    cellEditFeature,
    expandableFeature,
    treeViewFeature,
    csvExportFeature,
    paginationCurrentPage,
    paginationTotalPages,
    paginationSelectedPageSize,
  } = state;

  const virtualScroll = useVirtualScroll({
    itemCount: displayItems.length,
    itemSize: rowSize,
    viewportHeight: options.viewportHeight ?? 560,
    overscan: 3,
  });

  const itemsToRender = virtualizationEnabled
    ? displayItems.slice(virtualScroll.visibleRange.start, virtualScroll.visibleRange.end)
    : displayItems;

  const onViewportScroll = (event: React.UIEvent<HTMLDivElement>) => {
    virtualScroll.onScroll(event);
    const startIndex = Math.floor(event.currentTarget.scrollTop / rowSize);
    state.onViewportScroll(startIndex);
  };

  function renderDisplayItem(item: DisplayItem) {
    if (groupingFeature && state.isGroupItem(item)) {
      return (
        <button
          key={item.id}
          type="button"
          className="group-row ui-grid-row ui-grid-group-row"
          data-part="group-row"
          role="row"
          aria-expanded={!item.collapsed}
          style={{ gridColumn: '1 / -1', paddingInlineStart: `${item.depth * 1.25 + 1}rem` }}
          onClick={() => state.toggleGroup(item)}
        >
          <strong>
            {item.field}: {item.label}
          </strong>
          <span>
            {item.count} {labels.groupRowsSuffix}
          </span>
          <svg
            className="toggle-icon group-disclosure-icon"
            viewBox="0 0 24 24"
            aria-hidden="true"
            focusable={false}
          >
            <path d={item.collapsed ? 'M10 7l5 5-5 5z' : 'M7 10l5 5 5-5z'} />
          </svg>
          <span className="sr-only ui-grid-sr-only">{state.groupDisclosureLabel(item)}</span>
        </button>
      );
    }

    if (expandableFeature && state.isExpandableItem(item)) {
      const ctx = state.expandedContext(item.row);
      return (
        <div
          key={item.id}
          className="expandable-row ui-grid-row ui-grid-expandable-row"
          data-part="expandable-row"
          style={{ gridColumn: '1 / -1', minHeight: `${item.row.expandedRowHeight}px` }}
        >
          {expandableRenderer?.(ctx)}
        </div>
      );
    }

    if (item.kind !== 'row') return null;
    const rowItem = item as RowItem;

    return visibleColumns.map((column) => {
      const pinned = state.isPinned(column);
      const pinOffset = pinned ? state.pinnedOffset(column) : null;
      return (
      <div
        key={`${rowItem.row.id}-${column.name}`}
        className={`${cellClassName(rowItem, column)}${pinned ? ' is-pinned' : ''}`}
        data-part="body-cell"
        role="gridcell"
        tabIndex={0}
        data-row-id={rowItem.row.id}
        data-col-name={column.name}
        onFocus={() => state.focusCell(rowItem.row, column)}
        onClick={() => state.focusCell(rowItem.row, column)}
        onDoubleClick={(e) => state.handleCellDoubleClick(rowItem.row, column, e)}
        onKeyDown={(e) => state.handleCellKeyDown(rowItem.row, column, e)}
        style={{
          position: pinned ? 'sticky' : undefined,
          left: pinOffset?.side === 'left' ? pinOffset.offset : undefined,
          right: pinOffset?.side === 'right' ? pinOffset.offset : undefined,
          zIndex: pinned ? 2 : undefined,
        }}
      >
        <div
          className="cell-shell"
          style={{ paddingInlineStart: state.cellIndent(rowItem.row, column) }}
        >
          {treeViewFeature && state.showTreeToggle(rowItem.row, column) && (
            <button
              type="button"
              className="row-toggle row-toggle-tree"
              data-part="tree-toggle"
              aria-label={state.treeToggleLabel(rowItem.row)}
              aria-expanded={state.isTreeRowExpanded(rowItem.row)}
              onClick={(e) => state.toggleTreeRow(rowItem.row, e)}
            >
              <svg className="toggle-icon" viewBox="0 0 24 24" aria-hidden="true" focusable={false}>
                <path
                  d={state.isTreeRowExpanded(rowItem.row) ? 'M7 10l5 5 5-5z' : 'M10 7l5 5-5 5z'}
                />
              </svg>
            </button>
          )}
          {expandableFeature && state.showExpandToggle(rowItem.row, column) && (
            <button
              type="button"
              className="row-toggle row-toggle-expand"
              data-part="expand-toggle"
              aria-label={state.expandToggleLabel(rowItem.row)}
              aria-expanded={rowItem.row.expanded}
              onClick={(e) => state.toggleRowExpansion(rowItem.row, e)}
            >
              <svg className="toggle-icon" viewBox="0 0 24 24" aria-hidden="true" focusable={false}>
                <path d={rowItem.row.expanded ? 'M7 10l5 5 5-5z' : 'M10 7l5 5-5 5z'} />
              </svg>
            </button>
          )}
          <span className="cell-value">
            {cellEditFeature && state.isEditingCell(rowItem.row, column) ? (
              <input
                className="cell-editor"
                data-row-id={rowItem.row.id}
                data-col-name={column.name}
                aria-label={state.headerLabel(column)}
                type={state.editorInputType(column)}
                defaultValue={editingValue}
                onChange={(e) => state.updateEditingValue(e.target.value)}
                onKeyDown={(e) => state.handleEditorKeyDown(e)}
                onBlur={(e) => state.handleEditorBlur(e)}
              />
            ) : cellRenderer ? (
              (cellRenderer(state.cellContext(rowItem.row, column)) ??
              state.displayValue(rowItem.row, column))
            ) : (
              state.displayValue(rowItem.row, column)
            )}
          </span>
        </div>
      </div>
      );
    });
  }

  function cellClassName(item: RowItem, column: GridColumnDef): string {
    const classes = ['body-cell', 'ui-grid-cell'];
    if (state.isOddStripedRow(item)) classes.push('body-cell-odd');
    if (column.align === 'center') classes.push('align-center');
    if (column.align === 'end') classes.push('align-end');
    if (state.isFocusedCell(item.row, column)) classes.push('cell-focused');
    if (cellEditFeature && state.isEditingCell(item.row, column)) classes.push('cell-editing');
    return classes.join(' ');
  }

  function renderSortIcon(column: GridColumnDef) {
    const direction = state.sortDirection(column);
    switch (direction) {
      case 'asc':
        return (
          <svg viewBox="0 0 24 24" aria-hidden="true" focusable={false}>
            <path d="M12 5l-6 6h4v8h4v-8h4z" />
          </svg>
        );
      case 'desc':
        return (
          <svg viewBox="0 0 24 24" aria-hidden="true" focusable={false}>
            <path d="M12 19l6-6h-4V5h-4v8H6z" />
          </svg>
        );
      default:
        return (
          <svg viewBox="0 0 24 24" aria-hidden="true" focusable={false}>
            <path d="M7 6h10v2H7V6Zm0 5h7v2H7v-2Zm0 5h4v2H7v-2Z" />
          </svg>
        );
    }
  }

  return (
    <div className={`ui-grid-host ${className ?? ''}`} ref={gridContainerRef}>
      <section className="grid-shell ui-grid-shell" data-part="shell">
        <header className="grid-hero ui-grid-toolbar-shell" data-part="hero">
          <div>
            <p className="eyebrow">React wrapper for @ornery/ui-grid</p>
            <h1>{options.title ?? 'UI Grid'}</h1>
            <p className="deck">
              Familiar `gridOptions` and `onRegisterApi`, built with React hooks, virtualization,
              grouping, sorting, filtering, and column ordering.
            </p>
          </div>

          <div className="hero-actions">
            <button
              type="button"
              className="action action-secondary"
              data-part="action benchmark-action"
              onClick={() => state.runBenchmark()}
            >
              Benchmark
            </button>
            {csvExportFeature && (
              <button
                type="button"
                className="action action-secondary"
                data-part="action export-action"
                onClick={() => state.exportCsv()}
              >
                Export CSV
              </button>
            )}
            <div className="stats-card" data-part="stats-card">
              <span>{visibleRowCount}</span>
              <small>{labels.statsVisibleRows}</small>
            </div>
          </div>
        </header>

        <section
          className="metrics-strip"
          data-part="metrics"
          aria-label="Grid performance metrics"
        >
          <article data-part="metric-card">
            <strong>{pipelineMs.toFixed(2)} ms</strong>
            <span>pipeline</span>
          </article>
          <article data-part="metric-card">
            <strong>{virtualizationEnabled ? 'On' : 'Off'}</strong>
            <span>virtualization</span>
          </article>
          <article data-part="metric-card">
            <strong>{state.groupByColumns.length}</strong>
            <span>group columns</span>
          </article>
          <article data-part="metric-card">
            <strong>{benchmarkResult?.averageMs?.toFixed(2) || '—'}</strong>
            <span>benchmark avg</span>
          </article>
        </section>

        <section
          className="grid-frame ui-grid"
          data-part="grid-frame"
          role="grid"
          aria-label={options.title ?? 'Data grid'}
        >
          <div className="grid-toolbar" data-part="grid-toolbar">
            <div>
              <strong>{visibleRowCount}</strong>
              <span>
                {labels.toolbarOf} {totalRows} {labels.toolbarRows}
              </span>
            </div>
            <p>
              `gridOptions` compatibility layer: sorting, filtering, grouping, column moving,
              templating, and virtualized rendering.
            </p>
          </div>

          <div className="grid-table ui-grid-contents-wrapper" data-part="grid-table">
            {/* Header row */}
            <div
              className="header-grid ui-grid-header ui-grid-header-canvas"
              data-part="header"
              role="row"
              style={{ gridTemplateColumns }}
            >
              {visibleColumns.map((column) => {
                const pinned = state.isPinned(column);
                const pinOffset = pinned ? state.pinnedOffset(column) : null;
                return (
                <div
                  key={column.name}
                  className={`header-cell ui-grid-header-cell${sortingFeature && state.sortDirection(column) !== 'none' ? ' is-active' : ''}${pinned ? ' is-pinned' : ''}`}
                  data-part="header-cell"
                  role="columnheader"
                  aria-sort={sortingFeature ? (state.sortAriaSort(column) as any) : undefined}
                  style={{
                    position: pinned ? 'sticky' : undefined,
                    left: pinOffset?.side === 'left' ? pinOffset.offset : undefined,
                    right: pinOffset?.side === 'right' ? pinOffset.offset : undefined,
                    zIndex: pinned ? 2 : undefined,
                  }}
                >
                  <span className="header-label">{state.headerLabel(column)}</span>

                  <div className="header-actions">
                    {sortingFeature && (
                      <button
                        type="button"
                        className={`header-action${!state.isColumnSortable(column) ? ' header-action-disabled' : ''}`}
                        disabled={!state.isColumnSortable(column)}
                        aria-label={state.sortButtonLabel(column)}
                        title={state.sortButtonLabel(column)}
                        onClick={() => state.toggleSort(column)}
                      >
                        {renderSortIcon(column)}
                        <span className="sr-only ui-grid-sr-only">
                          {state.sortButtonLabel(column)}
                        </span>
                      </button>
                    )}

                    {groupingFeature &&
                      state.isGroupingEnabled() &&
                      column.enableGrouping !== false && (
                        <button
                          type="button"
                          className={`chip-action${state.isGrouped(column) ? ' chip-action-active' : ''}`}
                          data-part="group-toggle"
                          aria-label={state.groupingButtonLabel(column)}
                          title={state.groupingButtonLabel(column)}
                          onClick={(e) => state.toggleGrouping(column, e)}
                        >
                          <svg viewBox="0 0 24 24" aria-hidden="true" focusable={false}>
                            <path d="M4 6h8v4H4V6Zm0 8h8v4H4v-4Zm10-8h6v4h-6V6Zm0 8h6v4h-6v-4Z" />
                          </svg>
                          <span className="sr-only ui-grid-sr-only">
                            {state.groupingButtonLabel(column)}
                          </span>
                        </button>
                      )}
                    {state.pinningFeature &&
                      state.isPinningEnabled() &&
                      state.isColumnPinnable(column) && (
                        <button
                          type="button"
                          className={`chip-action${pinned ? ' chip-action-active' : ''}`}
                          data-part="pin-toggle"
                          aria-label={pinned ? labels.unpin : labels.pinLeft}
                          title={pinned ? labels.unpin : labels.pinLeft}
                          onClick={() => state.togglePin(column)}
                        >
                          <svg viewBox="0 0 24 24" aria-hidden="true" focusable={false}>
                            <path d="M16 12V4h1V2H7v2h1v8l-2 2v2h5v6l1 1 1-1v-6h5v-2l-2-2z" />
                          </svg>
                          <span className="sr-only ui-grid-sr-only">
                            {pinned ? labels.unpin : labels.pinLeft}
                          </span>
                        </button>
                      )}
                  </div>
                </div>
                );
              })}
            </div>

            {/* Filter row */}
            {filteringFeature && state.isFilteringEnabled() && (
              <div
                className="filter-grid ui-grid-header"
                data-part="filters"
                style={{ gridTemplateColumns }}
              >
                {visibleColumns.map((column) => {
                  const pinned = state.isPinned(column);
                  const pinOffset = pinned ? state.pinnedOffset(column) : null;
                  return (
                  <label
                    key={column.name}
                    className={`filter-cell ui-grid-filter-container${pinned ? ' is-pinned' : ''}`}
                    data-part="filter-cell"
                    style={{
                      position: pinned ? 'sticky' : undefined,
                      left: pinOffset?.side === 'left' ? pinOffset.offset : undefined,
                      right: pinOffset?.side === 'right' ? pinOffset.offset : undefined,
                      zIndex: pinned ? 2 : undefined,
                    }}
                  >
                    <span className="sr-only ui-grid-sr-only">
                      {labels.filterColumn} {state.headerLabel(column)}
                    </span>
                    <input
                      className="ui-grid-filter-input"
                      type="text"
                      defaultValue={state.filterValue(column.name)}
                      placeholder={state.filterPlaceholder(column)}
                      disabled={state.isFilterInputDisabled(column)}
                      onChange={(e) => state.updateFilter(column.name, e.target.value)}
                    />
                  </label>
                  );
                })}
              </div>
            )}

            {/* Body */}
            {displayItems.length > 0 ? (
              virtualizationEnabled ? (
                <div
                  className="grid-viewport ui-grid-viewport"
                  data-part="viewport"
                  ref={virtualScroll.viewportRef}
                  style={{ height: viewportHeightPx, overflow: 'auto', position: 'relative' }}
                  onScroll={onViewportScroll}
                >
                  <div style={{ height: `${virtualScroll.totalHeight}px`, position: 'relative' }}>
                    <div
                      className="body-grid ui-grid-canvas"
                      data-part="body"
                      role="rowgroup"
                      style={{
                        gridTemplateColumns,
                        position: 'absolute',
                        top: 0,
                        left: 0,
                        right: 0,
                        transform: `translateY(${virtualScroll.offsetY}px)`,
                      }}
                    >
                      {itemsToRender.map(renderDisplayItem)}
                    </div>
                  </div>
                </div>
              ) : (
                <div
                  className="body-grid ui-grid-canvas"
                  data-part="body"
                  role="rowgroup"
                  style={{ gridTemplateColumns }}
                >
                  {displayItems.map(renderDisplayItem)}
                </div>
              )
            ) : (
              <div className="empty-state ui-grid-no-row-overlay" data-part="empty-state">
                <strong>{options.emptyMessage ?? labels.emptyHeading}</strong>
                <p>{labels.emptyDescription}</p>
              </div>
            )}

            {/* Pagination footer */}
            {paginationFeature && state.showPaginationControls() && (
              <footer
                className="pagination-bar ui-grid-pagination"
                data-part="pagination"
                role="navigation"
                aria-label={labels.paginationPage}
              >
                <p>{state.paginationSummary()}</p>
                <div className="pagination-controls">
                  <button
                    type="button"
                    className="action action-secondary pagination-button"
                    aria-label={labels.paginationPrevious}
                    disabled={paginationCurrentPage <= 1}
                    onClick={() => state.previousPage()}
                  >
                    <svg
                      className="pagination-icon"
                      viewBox="0 0 24 24"
                      aria-hidden="true"
                      focusable={false}
                    >
                      <path d="M15.41 7.41L14 6l-6 6 6 6 1.41-1.41L10.83 12z" />
                    </svg>
                    <span className="sr-only">{labels.paginationPrevious}</span>
                  </button>
                  <span>
                    {labels.paginationPage} {paginationCurrentPage} {labels.paginationOf}{' '}
                    {paginationTotalPages}
                  </span>
                  <button
                    type="button"
                    className="action action-secondary pagination-button"
                    aria-label={labels.paginationNext}
                    disabled={paginationCurrentPage >= paginationTotalPages}
                    onClick={() => state.nextPage()}
                  >
                    <svg
                      className="pagination-icon"
                      viewBox="0 0 24 24"
                      aria-hidden="true"
                      focusable={false}
                    >
                      <path d="M8.59 16.59L10 18l6-6-6-6-1.41 1.41L13.17 12z" />
                    </svg>
                    <span className="sr-only">{labels.paginationNext}</span>
                  </button>
                  {state.pageSizeOptions().length > 0 && (
                    <label className="pagination-size">
                      <span className="sr-only">{labels.paginationRows}</span>
                      <select
                        aria-label={labels.paginationRows}
                        value={paginationSelectedPageSize}
                        onChange={(e) => state.onPageSizeChange(e.target.value)}
                      >
                        {state.pageSizeOptions().map((size) => (
                          <option key={size} value={size}>
                            {size}
                          </option>
                        ))}
                      </select>
                    </label>
                  )}
                </div>
              </footer>
            )}
          </div>
        </section>
      </section>
    </div>
  );
}

// src/app/grid/ui-grid.component.ts
import { NgTemplateOutlet } from '@angular/common';
import { CdkDrag, CdkDragDrop, CdkDropList, moveItemInArray } from '@angular/cdk/drag-drop';
import {
  CdkFixedSizeVirtualScroll,
  CdkVirtualForOf,
  CdkVirtualScrollViewport
} from '@angular/cdk/scrolling';
import {
  ChangeDetectionStrategy,
  Component,
  TemplateRef,
  ViewEncapsulation,
  computed,
  effect,
  input,
  signal
} from '@angular/core';
import { createGridApi, UiGridApi } from './grid.api';
import { FILTER_CONDITIONS, SORT_DIRECTIONS, SortDirection } from './grid.constants';
import {
  GridBenchmarkResult,
  GridCellTemplateContext,
  GridColumnDef,
  GridOptions,
  GridRecord,
  GridRow,
  SortState
} from './grid.models';
import { runColumnFilter, setupFilters } from './row-searcher';
import { getSortFn } from './row-sorter';
import { getCellValue, getPathValue, stringifyCellValue, titleize, toCsvValue } from './grid.utils';

interface GroupItem {
  kind: 'group';
  id: string;
  depth: number;
  field: string;
  label: string;
  count: number;
  collapsed: boolean;
}

interface RowItem {
  kind: 'row';
  id: string;
  row: GridRow;
}

type DisplayItem = GroupItem | RowItem;

interface PipelineResult {
  visibleRows: GridRow[];
  displayItems: DisplayItem[];
  virtualizationEnabled: boolean;
  pipelineMs: number;
}

@Component({
  selector: 'app-ui-grid',
  imports: [
    NgTemplateOutlet,
    CdkVirtualScrollViewport,
    CdkFixedSizeVirtualScroll,
    CdkVirtualForOf,
    CdkDropList,
    CdkDrag
  ],
  templateUrl: './ui-grid.component.html',
  styleUrl: './ui-grid.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.ShadowDom,
  host: {
    class: 'ui-grid-host'
  }
})
export class UiGridComponent {
  readonly options = input.required<GridOptions>();

  protected readonly activeFilters = signal<Record<string, string>>({});
  protected readonly groupByColumns = signal<string[]>([]);
  protected readonly collapsedGroups = signal<Record<string, boolean>>({});
  protected readonly columnOrder = signal<string[]>([]);
  protected readonly hiddenRowReasons = signal<Record<string, string[]>>({});
  protected readonly benchmarkResult = signal<GridBenchmarkResult | null>(null);
  protected readonly sortState = signal<SortState>({
    columnName: null,
    direction: SORT_DIRECTIONS.none
  });
  protected readonly gridApi: UiGridApi;

  private initializedGridId: string | null = null;
  private lastCanvasHeight = 0;
  private scrollEndHandle?: number;
  private scrolling = false;

  constructor() {
    this.gridApi = createGridApi({
      refresh: () => this.refresh(),
      getVisibleRows: () => this.pipeline().visibleRows,
      setRowInvisible: (row, reason) => this.setRowInvisible(row, reason),
      clearRowInvisible: (row, reason) => this.clearRowInvisible(row, reason),
      setFilter: (columnName, value) => this.updateFilter(columnName, value),
      clearAllFilters: () => this.clearAllFilters(),
      sortColumn: (columnName, direction) => this.sortColumn(columnName, direction),
      moveColumn: (fromIndex, toIndex) => this.moveColumn(fromIndex, toIndex),
      toggleGrouping: (columnName) => this.toggleGroupingByName(columnName),
      clearGrouping: () => this.groupByColumns.set([]),
      benchmark: (iterations) => this.runBenchmark(iterations),
      exportCsv: () => this.exportCsv()
    });

    effect(() => {
      const options = this.options();
      if (this.initializedGridId === options.id) {
        return;
      }

      this.initializedGridId = options.id;
      this.activeFilters.set({});
      this.hiddenRowReasons.set({});
      this.collapsedGroups.set({});
      this.columnOrder.set(options.columnDefs.map((column) => column.name));
      this.groupByColumns.set(options.grouping?.groupBy ?? []);
      const initialSort = options.columnDefs.find(
        (column) => column.sort?.direction && !column.sort.ignoreSort
      );
      this.sortState.set({
        columnName: initialSort?.name ?? null,
        direction: initialSort?.sort?.direction ?? SORT_DIRECTIONS.none
      });
      options.onRegisterApi?.(this.gridApi);
      this.gridApi.core.raise.renderingComplete(this.gridApi);
    });

    effect(() => {
      const pipeline = this.pipeline();
      this.gridApi.core.raise.rowsRendered(pipeline.visibleRows);
      this.gridApi.core.raise.rowsVisibleChanged(pipeline.visibleRows);

      const newHeight = pipeline.displayItems.length * this.rowSize();
      if (newHeight !== this.lastCanvasHeight) {
        this.gridApi.core.raise.canvasHeightChanged(this.lastCanvasHeight, newHeight);
        this.lastCanvasHeight = newHeight;
      }
    });
  }

  protected readonly visibleColumns = computed(() => {
    const order = this.columnOrder();
    return [...this.options().columnDefs]
      .filter((column) => column.visible !== false)
      .sort((left, right) => order.indexOf(left.name) - order.indexOf(right.name));
  });

  private readonly pipeline = computed<PipelineResult>(() => this.buildPipeline());

  protected readonly gridTemplateColumns = computed(() =>
    this.visibleColumns().map((column) => this.columnWidth(column)).join(' ')
  );
  protected readonly totalRows = computed(() => this.options().data.length);
  protected readonly visibleRowCount = computed(() => this.pipeline().visibleRows.length);
  protected readonly displayItems = computed(() => this.pipeline().displayItems);
  protected readonly pipelineMs = computed(() => this.pipeline().pipelineMs);
  protected readonly virtualizationEnabled = computed(() => this.pipeline().virtualizationEnabled);

  private buildPipeline(): PipelineResult {
    const startedAt = performance.now();
    const options = this.options();
    const rows = options.data.map((entity, index) => this.createRow(entity as GridRecord, index));
    const columns = this.visibleColumns();

    const filteredRows = rows.filter((row) => this.matchesFilters(row, columns));
    const sortedRows = this.sortRows(filteredRows, columns);
    const displayItems = this.buildDisplayItems(sortedRows);
    const virtualizationEnabled = this.isVirtualizationEnabled(displayItems.length);

    return {
      visibleRows: sortedRows,
      displayItems,
      virtualizationEnabled,
      pipelineMs: performance.now() - startedAt
    };
  }

  private createRow(entity: GridRecord, index: number): GridRow {
    const rowIdentity = this.options().rowIdentity?.(entity, index) ?? `${this.options().id}-${index}`;
    const row = new GridRow(rowIdentity, entity, index, this.rowSize());
    const hiddenReasons = this.hiddenRowReasons()[row.id] ?? [];

    for (const reason of hiddenReasons) {
      row.setThisRowInvisible(reason);
    }

    return row;
  }

  private matchesFilters(row: GridRow, columns: readonly GridColumnDef[]): boolean {
    if (!this.isFilteringEnabled()) {
      return row.visible;
    }

    const filters = this.activeFilters();
    for (const column of columns) {
      const term = filters[column.name]?.trim();
      if (!term || !this.isColumnFilterable(column)) {
        row.clearThisRowInvisible(`filter:${column.name}`);
        continue;
      }

      const parsedFilters = setupFilters([
        {
          ...(column.filter ?? { condition: FILTER_CONDITIONS.contains }),
          term
        }
      ]);

      const matchesAll = parsedFilters.every((filter) => runColumnFilter(row.entity, column, filter));
      if (!matchesAll) {
        row.setThisRowInvisible(`filter:${column.name}`);
        return false;
      }

      row.clearThisRowInvisible(`filter:${column.name}`);
    }

    return row.visible;
  }

  private sortRows(rows: readonly GridRow[], columns: readonly GridColumnDef[]): GridRow[] {
    const sortState = this.sortState();
    if (!sortState.columnName || sortState.direction === SORT_DIRECTIONS.none || !this.isSortingEnabled()) {
      return [...rows];
    }

    const sortColumn = columns.find((column) => column.name === sortState.columnName);
    if (!sortColumn || !this.isColumnSortable(sortColumn)) {
      return [...rows];
    }

    const sortFn = getSortFn(sortColumn, rows.map((row) => row.entity));
    const directionMultiplier = sortState.direction === SORT_DIRECTIONS.desc ? -1 : 1;

    return [...rows].sort((left, right) => {
      const leftValue = getCellValue(left.entity, sortColumn);
      const rightValue = getCellValue(right.entity, sortColumn);
      return sortFn(leftValue, rightValue) * directionMultiplier;
    });
  }

  private buildDisplayItems(rows: readonly GridRow[]): DisplayItem[] {
    if (!this.isGroupingEnabled() || this.groupByColumns().length === 0) {
      return rows.map((row) => ({ kind: 'row', id: row.id, row }));
    }

    return this.buildGroupedItems(rows, this.groupByColumns(), 0, '');
  }

  private buildGroupedItems(
    rows: readonly GridRow[],
    groupBy: readonly string[],
    depth: number,
    path: string
  ): DisplayItem[] {
    if (groupBy.length === 0) {
      return rows.map((row) => ({ kind: 'row', id: row.id, row }));
    }

    const [currentField, ...rest] = groupBy;
    const groups = new Map<string, GridRow[]>();

    for (const row of rows) {
      const value = stringifyCellValue(getPathValue(row.entity, currentField));
      const key = value || 'Unassigned';
      const bucket = groups.get(key) ?? [];
      bucket.push(row);
      groups.set(key, bucket);
    }

    const collapsedGroups = this.collapsedGroups();
    const items: DisplayItem[] = [];
    for (const [label, groupedRows] of groups) {
      const groupId = `${path}${currentField}:${label}`;
      const collapsed = collapsedGroups[groupId] ?? this.options().grouping?.startCollapsed ?? false;
      items.push({
        kind: 'group',
        id: groupId,
        depth,
        field: currentField,
        label,
        count: groupedRows.length,
        collapsed
      });

      if (!collapsed) {
        items.push(...this.buildGroupedItems(groupedRows, rest, depth + 1, `${groupId}|`));
      }
    }

    return items;
  }

  protected headerLabel(column: GridColumnDef): string {
    return column.displayName ?? titleize(column.name);
  }

  protected displayValue(row: GridRow, column: GridColumnDef): string {
    const context = this.cellContext(row, column);
    if (column.cellRenderer) {
      return column.cellRenderer(context);
    }

    return column.formatter
      ? column.formatter(context.value, row.entity)
      : stringifyCellValue(context.value);
  }

  protected cellTemplate(column: GridColumnDef): TemplateRef<GridCellTemplateContext> | null {
    return column.cellTemplate ?? null;
  }

  protected cellContext(row: GridRow, column: GridColumnDef): GridCellTemplateContext {
    const value = getCellValue(row.entity, column);
    return {
      $implicit: value,
      value,
      row: row.entity,
      column,
      rowIndex: row.index
    };
  }

  protected sortDirection(column: GridColumnDef): SortDirection {
    const sortState = this.sortState();
    return sortState.columnName === column.name ? sortState.direction : SORT_DIRECTIONS.none;
  }

  protected toggleSort(column: GridColumnDef): void {
    if (!this.isColumnSortable(column)) {
      return;
    }

    const currentDirection = this.sortDirection(column);
    const nextDirection =
      currentDirection === SORT_DIRECTIONS.none
        ? SORT_DIRECTIONS.asc
        : currentDirection === SORT_DIRECTIONS.asc
          ? SORT_DIRECTIONS.desc
          : SORT_DIRECTIONS.none;

    this.sortState.set({
      columnName: nextDirection === SORT_DIRECTIONS.none ? null : column.name,
      direction: nextDirection
    });
    this.gridApi.core.raise.sortChanged(
      nextDirection === SORT_DIRECTIONS.none ? null : column.name,
      nextDirection
    );
  }

  protected updateFilter(columnName: string, value: string): void {
    this.activeFilters.update((current) => ({
      ...current,
      [columnName]: value
    }));
    this.gridApi.core.raise.filterChanged(this.activeFilters());
  }

  protected clearAllFilters(): void {
    this.activeFilters.set({});
    this.gridApi.core.raise.filterChanged({});
  }

  protected columnWidth(column: GridColumnDef): string {
    return column.width ?? 'minmax(11rem, 1fr)';
  }

  protected isColumnSortable(column: GridColumnDef): boolean {
    return this.isSortingEnabled() && column.sortable !== false && column.enableSorting !== false;
  }

  protected isColumnFilterable(column: GridColumnDef): boolean {
    return this.isFilteringEnabled() && column.filterable !== false && column.enableFiltering !== false;
  }

  protected isGroupingEnabled(): boolean {
    return this.options().enableGrouping === true;
  }

  protected isSortingEnabled(): boolean {
    return this.options().enableSorting !== false;
  }

  protected isFilteringEnabled(): boolean {
    return this.options().enableFiltering !== false;
  }

  protected canMoveColumns(): boolean {
    return this.options().enableColumnMoving === true;
  }

  protected isGrouped(column: GridColumnDef): boolean {
    return this.groupByColumns().includes(column.name);
  }

  protected toggleGrouping(column: GridColumnDef, event?: Event): void {
    event?.stopPropagation();
    this.toggleGroupingByName(column.name);
  }

  private toggleGroupingByName(columnName: string): void {
    if (!this.isGroupingEnabled()) {
      return;
    }

    this.groupByColumns.update((current) =>
      current.includes(columnName)
        ? current.filter((name) => name !== columnName)
        : [...current, columnName]
    );
    this.gridApi.core.raise.groupingChanged(this.groupByColumns());
  }

  protected toggleGroup(item: GroupItem): void {
    this.collapsedGroups.update((current) => ({
      ...current,
      [item.id]: !current[item.id]
    }));
  }

  protected rowSize(): number {
    return this.options().rowHeight ?? 44;
  }

  protected viewportHeight(): string {
    return `${this.options().viewportHeight ?? 560}px`;
  }

  protected onColumnDrop(event: CdkDragDrop<readonly GridColumnDef[]>): void {
    if (event.previousIndex === event.currentIndex) {
      return;
    }

    this.moveColumn(event.previousIndex, event.currentIndex);
  }

  private moveColumn(fromIndex: number, toIndex: number): void {
    if (!this.canMoveColumns()) {
      return;
    }

    this.columnOrder.update((current) => {
      const next = [...current];
      moveItemInArray(next, fromIndex, toIndex);
      this.gridApi.core.raise.columnOrderChanged(next);
      return next;
    });
  }

  protected trackDisplayItem = (_index: number, item: DisplayItem): string => item.id;

  protected onViewportIndexChange(): void {
    if (!this.scrolling) {
      this.scrolling = true;
      this.gridApi.core.raise.scrollBegin();
    }

    if (this.scrollEndHandle) {
      window.clearTimeout(this.scrollEndHandle);
    }

    this.scrollEndHandle = window.setTimeout(() => {
      this.scrolling = false;
      this.gridApi.core.raise.scrollEnd();
    }, 120);
  }

  protected runBenchmark(iterations = this.options().benchmark?.iterations ?? 25): GridBenchmarkResult {
    const safeIterations = Math.max(1, iterations);
    const startedAt = performance.now();
    let lastResult = this.buildPipeline();

    for (let index = 1; index < safeIterations; index += 1) {
      lastResult = this.buildPipeline();
    }

    const totalMs = performance.now() - startedAt;
    const result: GridBenchmarkResult = {
      iterations: safeIterations,
      totalMs,
      averageMs: totalMs / safeIterations,
      visibleRows: lastResult.visibleRows.length,
      renderedItems: lastResult.displayItems.length
    };

    this.benchmarkResult.set(result);
    this.gridApi.core.raise.benchmarkComplete(result);
    return result;
  }

  protected exportCsv(): void {
    const columns = this.visibleColumns();
    const header = columns.map((column) => toCsvValue(this.headerLabel(column))).join(',');
    const rows = this.pipeline().visibleRows.map((row) =>
      columns.map((column) => toCsvValue(this.displayValue(row, column))).join(',')
    );
    const csv = [header, ...rows].join('\n');
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${this.options().id}.csv`;
    link.click();
    URL.revokeObjectURL(url);
  }

  private refresh(): void {
    this.activeFilters.update((current) => ({ ...current }));
  }

  private resolveRowId(row: GridRow | GridRecord | string): string {
    if (typeof row === 'string') {
      return row;
    }

    if (row instanceof GridRow) {
      return row.id;
    }

    const index = this.options().data.indexOf(row);
    return this.options().rowIdentity?.(row, index) ?? `${this.options().id}-${index}`;
  }

  private setRowInvisible(row: GridRow | GridRecord | string, reason = 'user'): void {
    const rowId = this.resolveRowId(row);
    this.hiddenRowReasons.update((current) => {
      const reasons = new Set(current[rowId] ?? []);
      reasons.add(reason);
      return { ...current, [rowId]: [...reasons] };
    });
  }

  private clearRowInvisible(row: GridRow | GridRecord | string, reason = 'user'): void {
    const rowId = this.resolveRowId(row);
    this.hiddenRowReasons.update((current) => {
      const reasons = new Set(current[rowId] ?? []);
      reasons.delete(reason);
      const next = { ...current };
      if (reasons.size === 0) {
        delete next[rowId];
      } else {
        next[rowId] = [...reasons];
      }
      return next;
    });
  }

  private sortColumn(columnName: string, direction?: SortDirection): void {
    const nextDirection = direction ?? SORT_DIRECTIONS.asc;
    this.sortState.set({ columnName, direction: nextDirection });
    this.gridApi.core.raise.sortChanged(columnName, nextDirection);
  }

  private isVirtualizationEnabled(itemCount: number): boolean {
    return this.options().enableVirtualization !== false
      && itemCount >= (this.options().virtualizationThreshold ?? 40);
  }
}

<section class="grid-shell ui-grid-shell" part="shell">
  <header class="grid-hero ui-grid-toolbar-shell" part="hero">
    <div>
      <p class="eyebrow">Angular 21 lift and shift</p>
      <h1>{{ options().title ?? 'UI Grid' }}</h1>
      <p class="deck">
        Familiar `gridOptions` and `onRegisterApi`, rebuilt with Angular 21 signals, CDK virtualization,
        native templates, grouping, sorting, filtering, and column ordering.
      </p>
    </div>

    <div class="hero-actions">
      <button type="button" class="action action-secondary" part="action benchmark-action" (click)="runBenchmark()">
        Benchmark
      </button>
      <button type="button" class="action action-secondary" part="action export-action" (click)="exportCsv()">
        Export CSV
      </button>
      <div class="stats-card" part="stats-card">
        <span>{{ visibleRowCount() }}</span>
        <small>visible rows</small>
      </div>
    </div>
  </header>

  <section class="metrics-strip" part="metrics" aria-label="Grid performance metrics">
    <article part="metric-card">
      <strong>{{ pipelineMs().toFixed(2) }} ms</strong>
      <span>pipeline</span>
    </article>
    <article part="metric-card">
      <strong>{{ virtualizationEnabled() ? 'On' : 'Off' }}</strong>
      <span>virtualization</span>
    </article>
    <article part="metric-card">
      <strong>{{ groupByColumns().length }}</strong>
      <span>group columns</span>
    </article>
    <article part="metric-card">
      <strong>{{ benchmarkResult()?.averageMs?.toFixed(2) || '—' }}</strong>
      <span>benchmark avg</span>
    </article>
  </section>

  <section class="grid-frame ui-grid" part="grid-frame">
    <div class="grid-toolbar" part="grid-toolbar">
      <div>
        <strong>{{ visibleRowCount() }}</strong>
        <span>of {{ totalRows() }} rows</span>
      </div>
      <p>
        `gridOptions` compatibility layer: sorting, filtering, grouping, column moving, templating,
        and virtualized rendering.
      </p>
    </div>

    <div class="grid-table ui-grid-contents-wrapper" part="grid-table">
      <div class="header-grid ui-grid-header ui-grid-header-canvas" part="header" [style.gridTemplateColumns]="gridTemplateColumns()" cdkDropList (cdkDropListDropped)="onColumnDrop($event)">
        @for (column of visibleColumns(); track column.name) {
          <div class="header-cell ui-grid-header-cell" part="header-cell" cdkDrag [class.is-active]="sortDirection(column) !== 'none'">
            <button
              type="button"
              class="header-action"
              [disabled]="!isColumnSortable(column)"
              [class.header-action-disabled]="!isColumnSortable(column)"
              (click)="toggleSort(column)">
              <span>{{ headerLabel(column) }}</span>
              <small>
                @if (sortDirection(column) === 'asc') {
                  Asc
                } @else if (sortDirection(column) === 'desc') {
                  Desc
                } @else {
                  Sort
                }
              </small>
            </button>

            @if (isGroupingEnabled() && column.enableGrouping !== false) {
              <button type="button" class="chip-action" part="group-toggle" [class.chip-action-active]="isGrouped(column)" (click)="toggleGrouping(column, $event)">
                {{ isGrouped(column) ? 'Grouped' : 'Group' }}
              </button>
            }
          </div>
        }
      </div>

      @if (isFilteringEnabled()) {
        <div class="filter-grid ui-grid-header" part="filters" [style.gridTemplateColumns]="gridTemplateColumns()">
          @for (column of visibleColumns(); track column.name) {
            <label class="filter-cell ui-grid-filter-container" part="filter-cell">
              <span class="sr-only ui-grid-sr-only">Filter {{ headerLabel(column) }}</span>
              <input
                class="ui-grid-filter-input"
                type="text"
                [value]="activeFilters()[column.name] || ''"
                [placeholder]="isColumnFilterable(column) ? 'Filter…' : 'Filter disabled'"
                [disabled]="!isColumnFilterable(column)"
                (input)="updateFilter(column.name, $any($event.target).value)" />
            </label>
          }
        </div>
      }

      @if (displayItems().length) {
        @if (virtualizationEnabled()) {
          <cdk-virtual-scroll-viewport class="grid-viewport ui-grid-viewport" part="viewport" [itemSize]="rowSize()" [style.height]="viewportHeight()" (scrolledIndexChange)="onViewportIndexChange()">
            <div class="body-grid ui-grid-canvas" part="body" [style.gridTemplateColumns]="gridTemplateColumns()">
              <ng-container *cdkVirtualFor="let item of displayItems(); trackBy: trackDisplayItem">
                @if (item.kind === 'group') {
                  <button type="button" class="group-row ui-grid-row ui-grid-group-row" part="group-row" [style.gridColumn]="'1 / -1'" [style.paddingInlineStart.rem]="item.depth * 1.25 + 1" (click)="toggleGroup(item)">
                    <strong>{{ item.field }}: {{ item.label }}</strong>
                    <span>{{ item.count }} rows</span>
                    <small>{{ item.collapsed ? 'Expand' : 'Collapse' }}</small>
                  </button>
                } @else {
                  @for (column of visibleColumns(); track column.name) {
                    <div class="body-cell ui-grid-cell" part="body-cell" [class.align-center]="column.align === 'center'" [class.align-end]="column.align === 'end'">
                      @if (cellTemplate(column); as template) {
                        <ng-container [ngTemplateOutlet]="template" [ngTemplateOutletContext]="cellContext(item.row, column)" />
                      } @else {
                        {{ displayValue(item.row, column) }}
                      }
                    </div>
                  }
                }
              </ng-container>
            </div>
          </cdk-virtual-scroll-viewport>
        } @else {
          <div class="body-grid ui-grid-canvas" part="body" [style.gridTemplateColumns]="gridTemplateColumns()">
            @for (item of displayItems(); track item.id) {
              @if (item.kind === 'group') {
                <button type="button" class="group-row ui-grid-row ui-grid-group-row" part="group-row" [style.gridColumn]="'1 / -1'" [style.paddingInlineStart.rem]="item.depth * 1.25 + 1" (click)="toggleGroup(item)">
                  <strong>{{ item.field }}: {{ item.label }}</strong>
                  <span>{{ item.count }} rows</span>
                  <small>{{ item.collapsed ? 'Expand' : 'Collapse' }}</small>
                </button>
              } @else {
                @for (column of visibleColumns(); track column.name) {
                  <div class="body-cell ui-grid-cell" part="body-cell" [class.align-center]="column.align === 'center'" [class.align-end]="column.align === 'end'">
                    @if (cellTemplate(column); as template) {
                      <ng-container [ngTemplateOutlet]="template" [ngTemplateOutletContext]="cellContext(item.row, column)" />
                    } @else {
                      {{ displayValue(item.row, column) }}
                    }
                  </div>
                }
              }
            }
          </div>
        }
      } @else {
        <div class="empty-state ui-grid-no-row-overlay" part="empty-state">
          <strong>{{ options().emptyMessage ?? 'No matching rows' }}</strong>
          <p>Adjust the active filters, grouping, or sort order.</p>
        </div>
      }
    </div>
  </section>
</section>
