// projects/ui-grid/src/lib/grid/ui-grid.component.ts
import { isPlatformBrowser } from '@angular/common';
import {
  AfterViewInit,
  ApplicationRef,
  ChangeDetectionStrategy,
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  EmbeddedViewRef,
  NgZone,
  OnDestroy,
  PLATFORM_ID,
  effect,
  inject,
  input,
  output,
  untracked,
} from '@angular/core';
import {
  defineStandaloneUiGridElement,
  UiGridStandaloneElement,
} from '@ornery/ui-grid-vanilla';
import type {
  FrameworkCellSlot,
  FrameworkSlotDelta,
} from '@ornery/ui-grid-vanilla';
import type {
  GridCellTemplateContext,
  GridColumnDef,
  GridOptions,
  GridRecord,
  GridTemplateRefLike,
  UiGridApi,
} from '@ornery/ui-grid-core';

const TAG_NAME = 'ui-grid-element';

@Component({
  selector: 'app-ui-grid',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  styleUrl: './ui-grid.component.scss',
  host: {
    ngSkipHydration: 'true',
  },
  template: ``,
})
export class UiGridComponent implements AfterViewInit, OnDestroy {
  readonly options = input<GridOptions>({
    id: '__ui-grid-pending__',
    data: [],
    columnDefs: [],
  });

  readonly apiReady = output<UiGridApi>();

  private readonly hostRef = inject<ElementRef<HTMLElement>>(ElementRef);
  private readonly platformId = inject(PLATFORM_ID);
  private readonly zone = inject(NgZone);
  private readonly appRef = inject(ApplicationRef);

  private gridElement: UiGridStandaloneElement | null = null;
  private elementReady = false;
  private listenerAttached = false;
  private slotViews = new Map<string, { view: EmbeddedViewRef<GridCellTemplateContext>; columnName: string; rowId: string }>();
  private templateColumns = new Map<string, GridTemplateRefLike<GridCellTemplateContext>>();
  private currentSlotColumnNames: string[] = [];

  constructor() {
    effect(() => {
      const opts = this.options();
      untracked(() => {
        if (!this.elementReady || !this.gridElement) return;
        this.applyOptions(opts);
      });
    });
  }

  async ngAfterViewInit(): Promise<void> {
    if (!isPlatformBrowser(this.platformId)) return;

    await this.zone.runOutsideAngular(async () => {
      await defineStandaloneUiGridElement(TAG_NAME);

      const el = document.createElement(TAG_NAME) as UiGridStandaloneElement;
      this.gridElement = el;
      this.hostRef.nativeElement.appendChild(el);

      this.applyOptions(this.options());
      this.elementReady = true;
    });
  }

  ngOnDestroy(): void {
    this.destroyAllSlotViews();

    if (this.gridElement) {
      this.gridElement.removeEventListener('cellSlotsChanged', this.onCellSlotsChanged);
      this.gridElement.remove();
      this.gridElement = null;
    }
  }

  private applyOptions(opts: GridOptions): void {
    const el = this.gridElement!;

    this.zone.runOutsideAngular(() => {
      // Extract Angular TemplateRef columns
      const cellSlotColumns: string[] = [];
      const newTemplateColumns = new Map<string, GridTemplateRefLike<GridCellTemplateContext>>();

      if (opts.columnDefs) {
        for (const col of opts.columnDefs) {
          if (col.cellTemplate?.createEmbeddedView) {
            cellSlotColumns.push(col.name);
            newTemplateColumns.set(col.name, col.cellTemplate);
          }
        }
      }

      // Register the event listener once
      if (!this.listenerAttached) {
        el.addEventListener('cellSlotsChanged', this.onCellSlotsChanged);
        this.listenerAttached = true;
      }

      // Determine if the template column set changed structurally
      const columnsChanged =
        cellSlotColumns.length !== this.currentSlotColumnNames.length ||
        cellSlotColumns.some((name, i) => name !== this.currentSlotColumnNames[i]);

      this.templateColumns = newTemplateColumns;

      if (columnsChanged) {
        // Structural change — destroy all views and reconfigure slots
        this.destroyAllSlotViews();
        this.currentSlotColumnNames = cellSlotColumns;
      }

      // Strip cellTemplate from columnDefs before passing to the element
      const cleanedColumnDefs: GridColumnDef[] | undefined = opts.columnDefs?.map((col) => {
        if (col.cellTemplate?.createEmbeddedView) {
          const { cellTemplate: _removed, ...rest } = col;
          return rest as GridColumnDef;
        }
        return col;
      });

      const wrappedOptions: GridOptions = {
        ...opts,
        columnDefs: cleanedColumnDefs,
        onRegisterApi: (api) => {
          this.zone.run(() => this.apiReady.emit(api as UiGridApi));
          opts.onRegisterApi?.(api);
        },
      };

      el.options = wrappedOptions;

      if (columnsChanged) {
        // Triggers re-render → flush → cellSlotsChanged with all cells as added
        el.setFrameworkRenderedSlots({ cells: cellSlotColumns });
      } else if (this.slotViews.size > 0) {
        // Data-only update — refresh existing view contexts in place
        this.updateSlotViewContexts(opts.data ?? []);
      }
    });
  }

  private updateSlotViewContexts(data: readonly GridRecord[]): void {
    const dataById = new Map<string, GridRecord>();
    for (const row of data) {
      const id = String(row['id'] ?? '');
      if (id) dataById.set(id, row);
    }

    for (const [, entry] of this.slotViews) {
      const row = dataById.get(entry.rowId);
      if (!row) continue;

      const col = this.findColumnDef(entry.columnName);
      const value = col?.field ? this.getNestedValue(row, col.field) : row[entry.columnName];

      entry.view.context.$implicit = value;
      entry.view.context.value = value;
      entry.view.context.row = row;
      entry.view.detectChanges();
    }
  }

  private findColumnDef(name: string): GridColumnDef | undefined {
    return this.options()?.columnDefs?.find((c) => c.name === name);
  }

  private getNestedValue(obj: GridRecord, field: string): unknown {
    const parts = field.split('.');
    let current: unknown = obj;
    for (const part of parts) {
      if (current == null || typeof current !== 'object') return undefined;
      current = (current as Record<string, unknown>)[part];
    }
    return current;
  }

  private destroyAllSlotViews(): void {
    const el = this.gridElement;
    for (const entry of this.slotViews.values()) {
      this.appRef.detachView(entry.view);
      entry.view.destroy();
    }
    this.slotViews.clear();
    if (el) {
      el.querySelectorAll(':scope > [slot]').forEach((node) => node.remove());
    }
  }

  private readonly onCellSlotsChanged = (event: Event): void => {
    const detail = (event as CustomEvent<FrameworkSlotDelta<FrameworkCellSlot>>).detail;
    const el = this.gridElement!;

    for (const slot of detail.removed) {
      const entry = this.slotViews.get(slot.slotName);
      if (entry) {
        this.appRef.detachView(entry.view);
        entry.view.destroy();
        this.slotViews.delete(slot.slotName);
      }
      el.querySelector(`:scope > [slot="${slot.slotName}"]`)?.remove();
    }

    for (const slot of detail.added) {
      const templateRef = this.templateColumns.get(slot.columnName);
      if (!templateRef?.createEmbeddedView) continue;

      const viewRef = templateRef.createEmbeddedView(slot.context) as EmbeddedViewRef<GridCellTemplateContext>;
      this.appRef.attachView(viewRef);
      viewRef.detectChanges();

      const wrapper = document.createElement('span');
      wrapper.setAttribute('slot', slot.slotName);
      for (const node of viewRef.rootNodes) {
        wrapper.appendChild(node);
      }
      el.appendChild(wrapper);

      const oldEntry = this.slotViews.get(slot.slotName);
      if (oldEntry) {
        this.appRef.detachView(oldEntry.view);
        oldEntry.view.destroy();
      }
      this.slotViews.set(slot.slotName, { view: viewRef, columnName: slot.columnName, rowId: slot.rowId });
    }
  };
}

<section class="grid-frame ui-grid" part="grid-frame" role="grid" [attr.aria-label]="options().title ?? 'Data grid'">

    <div class="grid-table ui-grid-contents-wrapper" part="grid-table"
      [style.height]="renderVirtualViewport() ? scrollContainerHeight() : null"
      [style.--ui-grid-header-sticky-top.px]="headerStickyHeight()">
      <div class="grid-header-strip" (wheel)="onStripWheel($event)">
      <div class="header-grid ui-grid-header ui-grid-header-canvas" part="header" role="row"
        [style.gridTemplateColumns]="gridTemplateColumns()" cdkDropList cdkDropListOrientation="horizontal"
        [cdkDropListData]="visibleColumns()" (cdkDropListDropped)="onColumnDrop($event)">
        @for (column of visibleColumns(); track column.name) {
        <div class="header-cell ui-grid-header-cell" part="header-cell" role="columnheader"
          [attr.data-col-name]="column.name"
          [attr.aria-sort]="sortingFeature ? sortAriaSort(column) : null" cdkDrag [cdkDragData]="column"
          [cdkDragDisabled]="!columnMovingFeature"
          [class.is-active]="sortingFeature && sortDirection(column) !== 'none'" [class.is-pinned]="isPinned(column)"
          [class.is-pin-menu-open]="isPinMenuOpen(column)"
          [style.position]="isPinned(column) ? 'sticky' : null"
          [style.left]="pinnedOffset(column)?.side === 'left' ? pinnedOffset(column)?.offset : null"
          [style.right]="pinnedOffset(column)?.side === 'right' ? pinnedOffset(column)?.offset : null"
          [style.zIndex]="isPinMenuOpen(column) ? 8 : isPinned(column) ? 2 : null">
          <span class="header-label">{{ headerLabel(column) }}</span>

          <div class="header-actions">
            @if (sortingFeature) {
            <button type="button" class="header-action" [disabled]="!isColumnSortable(column)"
              [class.header-action-disabled]="!isColumnSortable(column)" [attr.aria-label]="sortButtonLabel(column)"
              [attr.title]="sortButtonLabel(column)" (click)="toggleSort(column)">
              @switch (sortDirection(column)) {
              @case ('asc') {
              <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
                <path d="M12 5l-6 6h4v8h4v-8h4z"></path>
              </svg>
              }
              @case ('desc') {
              <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
                <path d="M12 19l6-6h-4V5h-4v8H6z"></path>
              </svg>
              }
              @default {
              <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
                <path d="M7 6h10v2H7V6Zm0 5h7v2H7v-2Zm0 5h4v2H7v-2Z"></path>
              </svg>
              }
              }
              <span class="sr-only ui-grid-sr-only">{{ sortButtonLabel(column) }}</span>
            </button>
            }

            @if (groupingFeature && isGroupingEnabled() && column.enableGrouping !== false) {
            <button type="button" class="chip-action" part="group-toggle" [class.chip-action-active]="isGrouped(column)"
              [attr.aria-label]="groupingButtonLabel(column)" [attr.title]="groupingButtonLabel(column)"
              (click)="toggleGrouping(column, $event)">
              <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
                <path d="M4 6h8v4H4V6Zm0 8h8v4H4v-4Zm10-8h6v4h-6V6Zm0 8h6v4h-6v-4Z"></path>
              </svg>
              <span class="sr-only ui-grid-sr-only">{{ groupingButtonLabel(column) }}</span>
            </button>
            }
            @if (pinningFeature && isPinningEnabled() && isColumnPinnable(column)) {
            <div class="pin-control" [class.pin-control-open]="isPinMenuOpen(column)" (click)="$event.stopPropagation()">
              <button type="button" class="chip-action pin-trigger" part="pin-toggle"
                [class.chip-action-active]="isPinned(column) || isPinMenuOpen(column)"
                [attr.aria-label]="pinButtonLabel(column)" [attr.title]="pinButtonLabel(column)"
                [attr.aria-haspopup]="isPinned(column) ? null : 'menu'"
                [attr.aria-expanded]="isPinned(column) ? null : isPinMenuOpen(column)"
                (click)="onPinTrigger(column, $event)">
                <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
                  <path d="M16 12V4h1V2H7v2h1v8l-2 2v2h5v6l1 1 1-1v-6h5v-2l-2-2z"></path>
                </svg>
                <span class="sr-only ui-grid-sr-only">{{ pinButtonLabel(column) }}</span>
              </button>

              <div class="pin-menu" part="pin-menu" role="menu" aria-label="Pin options"
                [attr.aria-hidden]="!isPinMenuOpen(column)">
                <button type="button" class="pin-menu-action" part="pin-left-action" role="menuitem"
                  [attr.aria-label]="labels().pinLeft" [attr.title]="labels().pinLeft"
                  [tabIndex]="isPinMenuOpen(column) ? 0 : -1"
                  (click)="choosePinDirection(column, 'left', $event)">
                  <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
                    <path d="M10 6 4 12l6 6v-4h10v-4H10V6z"></path>
                  </svg>
                  <span class="sr-only ui-grid-sr-only">{{ labels().pinLeft }}</span>
                </button>
                <button type="button" class="pin-menu-action" part="pin-right-action" role="menuitem"
                  [attr.aria-label]="labels().pinRight" [attr.title]="labels().pinRight"
                  [tabIndex]="isPinMenuOpen(column) ? 0 : -1"
                  (click)="choosePinDirection(column, 'right', $event)">
                  <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
                    <path d="M14 6v4H4v4h10v4l6-6-6-6z"></path>
                  </svg>
                  <span class="sr-only ui-grid-sr-only">{{ labels().pinRight }}</span>
                </button>
              </div>
            </div>
            }
          </div>

          @if (canResizeColumns()) {
          <button
            type="button"
            class="column-resizer"
            [attr.data-col-name]="column.name"
            aria-label="Resize {{ headerLabel(column) }} column"
            title="Drag to resize, double-click to auto fit"
            (mousedown)="handleHeaderResizeMouseDown(column, $event)"
            (dblclick)="autoSizeColumn(column, $event)">
          </button>
          }
        </div>
        }
      </div>
      </div>

      @if (filteringFeature && isFilteringEnabled()) {
      <div class="grid-filter-strip" (wheel)="onStripWheel($event)">
      <div class="filter-grid ui-grid-header" part="filters" [style.gridTemplateColumns]="gridTemplateColumns()">
        @for (column of visibleColumns(); track column.name) {
        <label class="filter-cell ui-grid-filter-container" part="filter-cell" [class.is-pinned]="isPinned(column)"
          [attr.data-col-name]="column.name"
          [style.position]="isPinned(column) ? 'sticky' : null"
          [style.left]="pinnedOffset(column)?.side === 'left' ? pinnedOffset(column)?.offset : null"
          [style.right]="pinnedOffset(column)?.side === 'right' ? pinnedOffset(column)?.offset : null"
          [style.zIndex]="isPinned(column) ? 2 : null">
          <span class="sr-only ui-grid-sr-only">{{ labels().filterColumn }} {{ headerLabel(column) }}</span>
          <input class="ui-grid-filter-input" type="text" [value]="filterValue(column.name)"
            [placeholder]="filterPlaceholder(column)" [disabled]="isFilterInputDisabled(column)"
            (input)="updateFilter(column.name, $any($event.target).value)" />
        </label>
        }
      </div>
      </div>
      }

      <ng-template #displayItemTemplate let-item>
        @if (groupingFeature && isGroupItem(item)) {
        <button type="button" class="group-row ui-grid-row ui-grid-group-row" part="group-row" role="row"
          [attr.aria-expanded]="!item.collapsed" [style.gridColumn]="'1 / -1'"
          [style.paddingInlineStart.rem]="item.depth * 1.25 + 1" (click)="toggleGroup(item)">
          <strong>{{ item.field }}: {{ item.label }}</strong>
          <span>{{ item.count }} {{ labels().groupRowsSuffix }}</span>
          <svg class="toggle-icon group-disclosure-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false">
            <path [attr.d]="item.collapsed ? 'M10 7l5 5-5 5z' : 'M7 10l5 5 5-5z'" />
          </svg>
          <span class="sr-only">{{ groupDisclosureLabel(item) }}</span>
        </button>
        } @else if (expandableFeature && isExpandableItem(item)) {
        <div class="expandable-row ui-grid-row ui-grid-expandable-row" part="expandable-row"
          [style.gridColumn]="'1 / -1'" [style.minHeight.px]="item.row.expandedRowHeight">
          @if (expandableTemplate(); as template) {
          <ng-container [ngTemplateOutlet]="template" [ngTemplateOutletContext]="expandedContext(item.row)" />
          }
        </div>
        } @else {
        @for (column of visibleColumns(); track column.name) {
        <div class="body-cell ui-grid-cell" part="body-cell" role="gridcell" tabindex="0"
          [attr.data-row-id]="item.row.id" [attr.data-col-name]="column.name"
          [class.body-cell-odd]="isOddStripedRow(item)" [class.align-center]="column.align === 'center'"
          [class.align-end]="column.align === 'end'" [class.row-focused]="isFocusedRow(item.row)"
          [class.cell-focused]="isFocusedCell(item.row, column)"
          [class.cell-editing]="cellEditFeature && isEditingCell(item.row, column)"
          (focus)="focusCell(item.row, column, $event)" (click)="focusCell(item.row, column, $event)"
          (dblclick)="handleCellDoubleClick(item.row, column, $event)"
          (keydown)="handleCellKeyDown(item.row, column, $event)" [class.is-pinned]="isPinned(column)"
          [style.position]="isPinned(column) ? 'sticky' : null"
          [style.left]="pinnedOffset(column)?.side === 'left' ? pinnedOffset(column)?.offset : null"
          [style.right]="pinnedOffset(column)?.side === 'right' ? pinnedOffset(column)?.offset : null"
          [style.zIndex]="isPinned(column) ? 2 : null">
          <div class="cell-shell" [style.paddingInlineStart]="cellIndent(item.row, column)">
            @if (treeViewFeature && showTreeToggle(item.row, column)) {
            <button type="button" class="row-toggle row-toggle-tree" part="tree-toggle"
              [attr.aria-label]="treeToggleLabel(item.row)" [attr.aria-expanded]="isTreeRowExpanded(item.row)"
              (click)="toggleTreeRow(item.row, $event)">
              <svg class="toggle-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false">
                <path [attr.d]="isTreeRowExpanded(item.row) ? 'M7 10l5 5 5-5z' : 'M10 7l5 5-5 5z'" />
              </svg>
            </button>
            }
            @if (expandableFeature && showExpandToggle(item.row, column)) {
            <button type="button" class="row-toggle row-toggle-expand" part="expand-toggle"
              [attr.aria-label]="expandToggleLabel(item.row)" [attr.aria-expanded]="item.row.expanded"
              (click)="toggleRowExpansion(item.row, $event)">
              <svg class="toggle-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false">
                <path [attr.d]="item.row.expanded ? 'M7 10l5 5 5-5z' : 'M10 7l5 5-5 5z'" />
              </svg>
            </button>
            }
            <span class="cell-value">
              @if (cellEditFeature && isEditingCell(item.row, column)) {
              <input class="cell-editor" [attr.data-row-id]="item.row.id" [attr.data-col-name]="column.name"
                [attr.aria-label]="headerLabel(column)" [type]="editorInputType(column)" [value]="editingValue()"
                (input)="updateEditingValue($any($event.target).value)" (keydown)="handleEditorKeyDown($event)"
                (blur)="handleEditorBlur($event)" />
              } @else if (cellTemplate(column); as template) {
              <ng-container [ngTemplateOutlet]="template" [ngTemplateOutletContext]="cellContext(item.row, column)" />
              } @else {
              {{ displayValue(item.row, column) }}
              }
            </span>
          </div>
        </div>
        }
        }
      </ng-template>

      <div class="grid-body-viewport"
        [style.overflow-y]="renderVirtualViewport() ? 'auto' : null"
        (scroll)="onBodyViewportScroll($event)">
      @if (displayItems().length) {
      @if (renderVirtualViewport()) {
      <div class="grid-virtual-spacer" [style.height.px]="virtualContentHeight()">
        <div class="body-grid ui-grid-canvas grid-virtual-body" part="body" role="rowgroup"
          [style.gridTemplateColumns]="gridTemplateColumns()" [style.top.px]="virtualContentOffset()">
          @for (item of renderedDisplayItems(); track item.id) {
          <ng-container [ngTemplateOutlet]="displayItemTemplate" [ngTemplateOutletContext]="{ $implicit: item }" />
          }
        </div>
      </div>
      } @else {
      <div class="body-grid ui-grid-canvas" part="body" role="rowgroup"
        [style.gridTemplateColumns]="gridTemplateColumns()">
        @for (item of renderedDisplayItems(); track item.id) {
        <ng-container [ngTemplateOutlet]="displayItemTemplate" [ngTemplateOutletContext]="{ $implicit: item }" />
        }
      </div>
      }
      } @else {
      <div class="empty-state ui-grid-no-row-overlay" part="empty-state">
        <strong>{{ options().emptyMessage ?? labels().emptyHeading }}</strong>
        <p>{{ labels().emptyDescription }}</p>
      </div>
      }
      </div>

      @if (paginationFeature && showPaginationControls()) {
      <footer class="pagination-bar ui-grid-pagination" part="pagination" role="navigation"
        [attr.aria-label]="labels().paginationPage">
        <p>{{ paginationSummary() }}</p>
        <div class="pagination-controls">
          <button type="button" class="action action-secondary pagination-button"
            [attr.aria-label]="labels().paginationPrevious" [disabled]="paginationCurrentPage() <= 1"
            (click)="previousPage()">
            <svg class="pagination-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false">
              <path d="M15.41 7.41L14 6l-6 6 6 6 1.41-1.41L10.83 12z" />
            </svg>
            <span class="sr-only">{{ labels().paginationPrevious }}</span>
          </button>
          <span>{{ labels().paginationPage }} {{ paginationCurrentPage() }} {{ labels().paginationOf }} {{
            paginationTotalPages() }}</span>
          <button type="button" class="action action-secondary pagination-button"
            [attr.aria-label]="labels().paginationNext" [disabled]="paginationCurrentPage() >= paginationTotalPages()"
            (click)="nextPage()">
            <svg class="pagination-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false">
              <path d="M8.59 16.59L10 18l6-6-6-6-1.41 1.41L13.17 12z" />
            </svg>
            <span class="sr-only">{{ labels().paginationNext }}</span>
          </button>
          @if (pageSizeOptions().length > 0) {
          <label class="pagination-size">
            <span class="sr-only">{{ labels().paginationRows }}</span>
            <select [attr.aria-label]="labels().paginationRows" [value]="paginationSelectedPageSize()"
              (change)="onPageSizeChange($any($event.target).value)">
              @for (size of pageSizeOptions(); track size) {
              <option [value]="size">{{ size }}</option>
              }
            </select>
          </label>
          }
        </div>
      </footer>
      }
    </div>
  </section>

// projects/ui-grid-react/src/UiGrid.tsx
import React from 'react';
import type {
  GridOptions,
  GridCellTemplateContext,
  GridExpandableTemplateContext,
  GridHeaderTemplateContext,
  UiGridApi,
  GridColumnDef,
  GridRow,
} from '@ornery/ui-grid-core';
import type { DisplayItem, RowItem } from '@ornery/ui-grid-core';
import { useGridState } from './useGridState';
import { useVirtualScroll } from './useVirtualScroll';

export interface UiGridProps {
  options: GridOptions;
  onRegisterApi?: (api: UiGridApi) => void;
  cellRenderer?: (context: GridCellTemplateContext) => React.ReactNode;
  headerRenderer?: (context: GridHeaderTemplateContext) => React.ReactNode;
  expandableRenderer?: (context: GridExpandableTemplateContext) => React.ReactNode;
  className?: string;
}

export function UiGrid({
  options,
  onRegisterApi,
  cellRenderer,
  headerRenderer,
  expandableRenderer,
  className,
}: UiGridProps) {
  const state = useGridState(options, onRegisterApi);

  const {
    pipeline,
    visibleColumns,
    labels,
    gridTemplateColumns,
    gridContainerRef,
    displayItems,
    virtualizationEnabled,
    rowSize,
    editingValue,
    autoViewportHeight,
    sortingFeature,
    filteringFeature,
    groupingFeature,
    paginationFeature,
    cellEditFeature,
    expandableFeature,
    treeViewFeature,
    columnMovingFeature,
    paginationCurrentPage,
    paginationTotalPages,
    paginationSelectedPageSize,
  } = state;

  const headerGridRef = React.useRef<HTMLDivElement | null>(null);
  const filterGridRef = React.useRef<HTMLDivElement | null>(null);
  const [headerStickyHeight, setHeaderStickyHeight] = React.useState(0);
  const [filterStickyHeight, setFilterStickyHeight] = React.useState(0);
  const stickyChromeHeight = headerStickyHeight + filterStickyHeight;
  // Prefer the explicit viewportHeight, otherwise fall back to the container
  // height measured by the autoresize observer so the grid fills its parent
  // by default. The 560 fallback only applies before the first measurement.
  const resolvedViewportHeight =
    options.viewportHeight ?? (autoViewportHeight && autoViewportHeight > 0 ? autoViewportHeight : 560);
  const bodyViewportHeight = Math.max(rowSize, resolvedViewportHeight - stickyChromeHeight);

  const virtualScroll = useVirtualScroll({
    itemCount: displayItems.length,
    itemSize: rowSize,
    viewportHeight: bodyViewportHeight,
    overscan: 3,
  });

  const [openPinMenuColumn, setOpenPinMenuColumn] = React.useState<string | null>(null);
  const [draggedColumnName, setDraggedColumnName] = React.useState<string | null>(null);
  const [dropTargetColumnName, setDropTargetColumnName] = React.useState<string | null>(null);
  const scrollContainerHeight = `${resolvedViewportHeight}px`;

  function renderHeaderContent(column: GridColumnDef): React.ReactNode {
    const value = state.headerLabel(column);
    const context: GridHeaderTemplateContext = {
      $implicit: value,
      value,
      column,
    };

    if (headerRenderer) {
      return headerRenderer(context) ?? value;
    }

    if (column.headerRenderer) {
      return column.headerRenderer(context);
    }

    return value;
  }

  const eventPathIncludesClass = React.useCallback((event: Event, className: string): boolean => {
    const eventPath =
      typeof event.composedPath === 'function'
        ? event.composedPath()
        : event.target
          ? [event.target]
          : [];

    return eventPath.some((target) => {
      if (!target || typeof target !== 'object' || !('classList' in target)) {
        return false;
      }

      const classList = (target as { classList?: DOMTokenList }).classList;
      return classList?.contains(className) ?? false;
    });
  }, []);

  const isPinMenuOpen = React.useCallback(
    (column: GridColumnDef) => openPinMenuColumn === column.name,
    [openPinMenuColumn],
  );

  const pinButtonLabel = React.useCallback(
    (column: GridColumnDef) => (state.isPinned(column) ? labels.unpin : labels.pinColumn),
    [labels, state],
  );

  const onPinTrigger = React.useCallback(
    (column: GridColumnDef, event?: React.MouseEvent) => {
      event?.stopPropagation();
      if (state.isPinned(column)) {
        setOpenPinMenuColumn(null);
        state.gridApi.pinning.pinColumn(column.name, 'none');
        return;
      }

      setOpenPinMenuColumn((current) => (current === column.name ? null : column.name));
    },
    [state],
  );

  const choosePinDirection = React.useCallback(
    (column: GridColumnDef, direction: 'left' | 'right', event?: React.MouseEvent) => {
      event?.stopPropagation();
      setOpenPinMenuColumn(null);
      state.gridApi.pinning.pinColumn(column.name, direction);
    },
    [state],
  );

  const handleHeaderDragStart = React.useCallback(
    (column: GridColumnDef, event: React.DragEvent<HTMLDivElement>) => {
      if (!columnMovingFeature) {
        event.preventDefault();
        return;
      }

      setDraggedColumnName(column.name);
      setDropTargetColumnName(null);
      event.dataTransfer.effectAllowed = 'move';
      event.dataTransfer.setData('text/plain', column.name);
    },
    [columnMovingFeature],
  );

  const handleHeaderDragOver = React.useCallback(
    (column: GridColumnDef, event: React.DragEvent<HTMLDivElement>) => {
      if (!columnMovingFeature || !draggedColumnName || draggedColumnName === column.name) {
        return;
      }

      event.preventDefault();
      event.dataTransfer.dropEffect = 'move';
      setDropTargetColumnName(column.name);
    },
    [columnMovingFeature, draggedColumnName],
  );

  const handleHeaderDrop = React.useCallback(
    (column: GridColumnDef, event: React.DragEvent<HTMLDivElement>) => {
      event.preventDefault();

      if (!columnMovingFeature) {
        return;
      }

      const sourceColumnName = draggedColumnName ?? event.dataTransfer.getData('text/plain');
      setDraggedColumnName(null);
      setDropTargetColumnName(null);

      if (!sourceColumnName || sourceColumnName === column.name) {
        return;
      }

      state.moveVisibleColumn(sourceColumnName, column.name);
    },
    [columnMovingFeature, draggedColumnName, state],
  );

  const handleHeaderDragEnd = React.useCallback(() => {
    setDraggedColumnName(null);
    setDropTargetColumnName(null);
  }, []);

  React.useLayoutEffect(() => {
    setHeaderStickyHeight(headerGridRef.current?.offsetHeight ?? 0);
    setFilterStickyHeight(filterGridRef.current?.offsetHeight ?? 0);
  }, [visibleColumns, filteringFeature, options.enableFiltering]);

  React.useLayoutEffect(() => {
    const headerElement = headerGridRef.current;
    const filterElement = filterGridRef.current;
    if (typeof ResizeObserver === 'undefined' || (!headerElement && !filterElement)) {
      return;
    }

    const observer = new ResizeObserver(() => {
      setHeaderStickyHeight(headerGridRef.current?.offsetHeight ?? 0);
      setFilterStickyHeight(filterGridRef.current?.offsetHeight ?? 0);
    });

    if (headerElement) {
      observer.observe(headerElement);
    }
    if (filterElement) {
      observer.observe(filterElement);
    }

    return () => observer.disconnect();
  }, []);

  React.useEffect(() => {
    if (!openPinMenuColumn) {
      return;
    }

    const handleDocumentClick = (event: MouseEvent) => {
      if (eventPathIncludesClass(event, 'pin-control')) {
        return;
      }

      setOpenPinMenuColumn(null);
    };

    const handleDocumentEscape = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        setOpenPinMenuColumn(null);
      }
    };

    document.addEventListener('click', handleDocumentClick);
    document.addEventListener('keydown', handleDocumentEscape);

    return () => {
      document.removeEventListener('click', handleDocumentClick);
      document.removeEventListener('keydown', handleDocumentEscape);
    };
  }, [eventPathIncludesClass, openPinMenuColumn]);

  const itemsToRender = virtualizationEnabled
    ? displayItems.slice(virtualScroll.visibleRange.start, virtualScroll.visibleRange.end)
    : displayItems;

  const onGridTableScroll = (event: React.UIEvent<HTMLDivElement>) => {
    const bodyScrollTop = Math.max(0, event.currentTarget.scrollTop - stickyChromeHeight);
    virtualScroll.setScrollTop(bodyScrollTop);
    const startIndex = Math.floor(bodyScrollTop / rowSize);
    state.onViewportScroll(startIndex);
  };

  function renderDisplayItem(item: DisplayItem) {
    if (groupingFeature && state.isGroupItem(item)) {
      return (
        <button
          key={item.id}
          type="button"
          className="group-row ui-grid-row ui-grid-group-row"
          data-part="group-row"
          role="row"
          aria-expanded={!item.collapsed}
          style={{ gridColumn: '1 / -1', paddingInlineStart: `${item.depth * 1.25 + 1}rem` }}
          onClick={() => state.toggleGroup(item)}
        >
          <strong>
            {item.field}: {item.label}
          </strong>
          <span>
            {item.count} {labels.groupRowsSuffix}
          </span>
          <svg
            className="toggle-icon group-disclosure-icon"
            viewBox="0 0 24 24"
            aria-hidden="true"
            focusable={false}
          >
            <path d={item.collapsed ? 'M10 7l5 5-5 5z' : 'M7 10l5 5 5-5z'} />
          </svg>
          <span className="sr-only ui-grid-sr-only">{state.groupDisclosureLabel(item)}</span>
        </button>
      );
    }

    if (expandableFeature && state.isExpandableItem(item)) {
      const ctx = state.expandedContext(item.row);
      return (
        <div
          key={item.id}
          className="expandable-row ui-grid-row ui-grid-expandable-row"
          data-part="expandable-row"
          style={{ gridColumn: '1 / -1', minHeight: `${item.row.expandedRowHeight}px` }}
        >
          {expandableRenderer?.(ctx)}
        </div>
      );
    }

    if (item.kind !== 'row') return null;
    const rowItem = item as RowItem;

    return visibleColumns.map((column) => {
      const pinned = state.isPinned(column);
      const pinOffset = pinned ? state.pinnedOffset(column) : null;
      return (
        <div
          key={`${rowItem.row.id}-${column.name}`}
          className={`${cellClassName(rowItem, column)}${pinned ? ' is-pinned' : ''}`}
          data-part="body-cell"
          role="gridcell"
          tabIndex={0}
          data-row-id={rowItem.row.id}
          data-col-name={column.name}
          onFocus={() => state.focusCell(rowItem.row, column)}
          onClick={() => state.focusCell(rowItem.row, column)}
          onDoubleClick={(e) => state.handleCellDoubleClick(rowItem.row, column, e)}
          onKeyDown={(e) => state.handleCellKeyDown(rowItem.row, column, e)}
          style={{
            position: pinned ? 'sticky' : undefined,
            left: pinOffset?.side === 'left' ? pinOffset.offset : undefined,
            right: pinOffset?.side === 'right' ? pinOffset.offset : undefined,
            zIndex: pinned ? 2 : undefined,
          }}
        >
          <div
            className="cell-shell"
            style={{ paddingInlineStart: state.cellIndent(rowItem.row, column) }}
          >
            {treeViewFeature && state.showTreeToggle(rowItem.row, column) && (
              <button
                type="button"
                className="row-toggle row-toggle-tree"
                data-part="tree-toggle"
                aria-label={state.treeToggleLabel(rowItem.row)}
                aria-expanded={state.isTreeRowExpanded(rowItem.row)}
                onClick={(e) => state.toggleTreeRow(rowItem.row, e)}
              >
                <svg
                  className="toggle-icon"
                  viewBox="0 0 24 24"
                  aria-hidden="true"
                  focusable={false}
                >
                  <path
                    d={state.isTreeRowExpanded(rowItem.row) ? 'M7 10l5 5 5-5z' : 'M10 7l5 5-5 5z'}
                  />
                </svg>
              </button>
            )}
            {expandableFeature && state.showExpandToggle(rowItem.row, column) && (
              <button
                type="button"
                className="row-toggle row-toggle-expand"
                data-part="expand-toggle"
                aria-label={state.expandToggleLabel(rowItem.row)}
                aria-expanded={rowItem.row.expanded}
                onClick={(e) => state.toggleRowExpansion(rowItem.row, e)}
              >
                <svg
                  className="toggle-icon"
                  viewBox="0 0 24 24"
                  aria-hidden="true"
                  focusable={false}
                >
                  <path d={rowItem.row.expanded ? 'M7 10l5 5 5-5z' : 'M10 7l5 5-5 5z'} />
                </svg>
              </button>
            )}
            <span className="cell-value">
              {cellEditFeature && state.isEditingCell(rowItem.row, column) ? (
                <input
                  className="cell-editor"
                  data-row-id={rowItem.row.id}
                  data-col-name={column.name}
                  aria-label={state.headerLabel(column)}
                  type={state.editorInputType(column)}
                  defaultValue={editingValue}
                  onChange={(e) => state.updateEditingValue(e.target.value)}
                  onKeyDown={(e) => state.handleEditorKeyDown(e)}
                  onBlur={(e) => state.handleEditorBlur(e)}
                />
              ) : cellRenderer ? (
                (cellRenderer(state.cellContext(rowItem.row, column)) ??
                state.displayValue(rowItem.row, column))
              ) : (
                state.displayValue(rowItem.row, column)
              )}
            </span>
          </div>
        </div>
      );
    });
  }

  function cellClassName(item: RowItem, column: GridColumnDef): string {
    const classes = ['body-cell', 'ui-grid-cell'];
    if (state.isOddStripedRow(item)) classes.push('body-cell-odd');
    if (column.align === 'center') classes.push('align-center');
    if (column.align === 'end') classes.push('align-end');
    if (state.isFocusedCell(item.row, column)) classes.push('cell-focused');
    if (state.isFocusedRow(item.row)) classes.push('row-focused');
    if (cellEditFeature && state.isEditingCell(item.row, column)) classes.push('cell-editing');
    return classes.join(' ');
  }

  function renderSortIcon(column: GridColumnDef) {
    const direction = state.sortDirection(column);
    switch (direction) {
      case 'asc':
        return (
          <svg viewBox="0 0 24 24" aria-hidden="true" focusable={false}>
            <path d="M12 5l-6 6h4v8h4v-8h4z" />
          </svg>
        );
      case 'desc':
        return (
          <svg viewBox="0 0 24 24" aria-hidden="true" focusable={false}>
            <path d="M12 19l6-6h-4V5h-4v8H6z" />
          </svg>
        );
      default:
        return (
          <svg viewBox="0 0 24 24" aria-hidden="true" focusable={false}>
            <path d="M7 6h10v2H7V6Zm0 5h7v2H7v-2Zm0 5h4v2H7v-2Z" />
          </svg>
        );
    }
  }

  return (
    <div className={`ui-grid-host ${className ?? ''}`} ref={gridContainerRef}>
      <section
        className="grid-frame ui-grid"
        data-part="grid-frame"
        role="grid"
        aria-label={options.title ?? 'Data grid'}
      >
        <div
          className="grid-table ui-grid-contents-wrapper"
          data-part="grid-table"
          style={
            virtualizationEnabled ? { height: scrollContainerHeight, overflowY: 'auto' } : undefined
          }
          onScroll={virtualizationEnabled ? onGridTableScroll : undefined}
        >
          <div
            className="header-grid ui-grid-header ui-grid-header-canvas"
            data-part="header"
            role="row"
            ref={headerGridRef}
            style={{ gridTemplateColumns }}
          >
            {visibleColumns.map((column) => {
              const pinned = state.isPinned(column);
              const pinOffset = pinned ? state.pinnedOffset(column) : null;
              const pinMenuOpen = isPinMenuOpen(column);
              return (
                <div
                  key={column.name}
                  className={`header-cell ui-grid-header-cell${sortingFeature && state.sortDirection(column) !== 'none' ? ' is-active' : ''}${pinned ? ' is-pinned' : ''}${pinMenuOpen ? ' is-pin-menu-open' : ''}${draggedColumnName === column.name ? ' is-dragging' : ''}${dropTargetColumnName === column.name ? ' is-drag-target' : ''}`}
                  data-part="header-cell"
                  data-col-name={column.name}
                  aria-sort={sortingFeature ? (state.sortAriaSort(column) as any) : undefined}
                  draggable={columnMovingFeature}
                  onDragStart={(event) => handleHeaderDragStart(column, event)}
                  onDragOver={(event) => handleHeaderDragOver(column, event)}
                  onDrop={(event) => handleHeaderDrop(column, event)}
                  onDragEnd={handleHeaderDragEnd}
                  onDragLeave={() => {
                    if (dropTargetColumnName === column.name) {
                      setDropTargetColumnName(null);
                    }
                  }}
                  style={{
                    position: pinned ? 'sticky' : undefined,
                    left: pinOffset?.side === 'left' ? pinOffset.offset : undefined,
                    right: pinOffset?.side === 'right' ? pinOffset.offset : undefined,
                    zIndex: pinMenuOpen ? 8 : pinned ? 2 : undefined,
                  }}
                >
                  <span className="header-label">{renderHeaderContent(column)}</span>

                  <div className="header-actions">
                    {sortingFeature && (
                      <button
                        type="button"
                        className={`header-action${!state.isColumnSortable(column) ? ' header-action-disabled' : ''}`}
                        disabled={!state.isColumnSortable(column)}
                        aria-label={state.sortButtonLabel(column)}
                        title={state.sortButtonLabel(column)}
                        onClick={() => state.toggleSort(column)}
                      >
                        {renderSortIcon(column)}
                        <span className="sr-only ui-grid-sr-only">
                          {state.sortButtonLabel(column)}
                        </span>
                      </button>
                    )}

                    {groupingFeature &&
                      state.isGroupingEnabled() &&
                      column.enableGrouping !== false && (
                        <button
                          type="button"
                          className={`chip-action${state.isGrouped(column) ? ' chip-action-active' : ''}`}
                          data-part="group-toggle"
                          aria-label={state.groupingButtonLabel(column)}
                          title={state.groupingButtonLabel(column)}
                          onClick={(e) => state.toggleGrouping(column, e)}
                        >
                          <svg viewBox="0 0 24 24" aria-hidden="true" focusable={false}>
                            <path d="M4 6h8v4H4V6Zm0 8h8v4H4v-4Zm10-8h6v4h-6V6Zm0 8h6v4h-6v-4Z" />
                          </svg>
                          <span className="sr-only ui-grid-sr-only">
                            {state.groupingButtonLabel(column)}
                          </span>
                        </button>
                      )}

                    {state.pinningFeature &&
                      state.isPinningEnabled() &&
                      state.isColumnPinnable(column) && (
                        <div
                          className={`pin-control${pinMenuOpen ? ' pin-control-open' : ''}`}
                          onClick={(event) => event.stopPropagation()}
                        >
                          <button
                            type="button"
                            className={`chip-action pin-trigger${pinned || pinMenuOpen ? ' chip-action-active' : ''}`}
                            data-part="pin-toggle"
                            aria-label={pinButtonLabel(column)}
                            title={pinButtonLabel(column)}
                            aria-haspopup={pinned ? undefined : 'menu'}
                            aria-expanded={pinned ? undefined : pinMenuOpen}
                            onClick={(event) => onPinTrigger(column, event)}
                          >
                            <svg viewBox="0 0 24 24" aria-hidden="true" focusable={false}>
                              <path d="M16 12V4h1V2H7v2h1v8l-2 2v2h5v6l1 1 1-1v-6h5v-2l-2-2z" />
                            </svg>
                            <span className="sr-only ui-grid-sr-only">{pinButtonLabel(column)}</span>
                          </button>

                          <div
                            className="pin-menu"
                            data-part="pin-menu"
                            role="menu"
                            aria-label="Pin options"
                            aria-hidden={!pinMenuOpen}
                          >
                            <button
                              type="button"
                              className="pin-menu-action"
                              data-part="pin-left-action"
                              role="menuitem"
                              aria-label={labels.pinLeft}
                              title={labels.pinLeft}
                              tabIndex={pinMenuOpen ? 0 : -1}
                              onClick={(event) => choosePinDirection(column, 'left', event)}
                            >
                              <svg viewBox="0 0 24 24" aria-hidden="true" focusable={false}>
                                <path d="M10 6 4 12l6 6v-4h10v-4H10V6z" />
                              </svg>
                              <span className="sr-only ui-grid-sr-only">{labels.pinLeft}</span>
                            </button>
                            <button
                              type="button"
                              className="pin-menu-action"
                              data-part="pin-right-action"
                              role="menuitem"
                              aria-label={labels.pinRight}
                              title={labels.pinRight}
                              tabIndex={pinMenuOpen ? 0 : -1}
                              onClick={(event) => choosePinDirection(column, 'right', event)}
                            >
                              <svg viewBox="0 0 24 24" aria-hidden="true" focusable={false}>
                                <path d="M14 6v4H4v4h10v4l6-6-6-6z" />
                              </svg>
                              <span className="sr-only ui-grid-sr-only">{labels.pinRight}</span>
                            </button>
                          </div>
                        </div>
                      )}
                  </div>

                  {state.canResizeColumns() && (
                    <button
                      type="button"
                      className="column-resizer"
                      data-col-name={column.name}
                      aria-label={`Resize ${state.headerLabel(column)} column`}
                      title="Drag to resize, double-click to auto fit"
                      onMouseDown={(event) => state.handleHeaderResizeMouseDown(column, event)}
                      onDoubleClick={(event) => state.autoSizeColumn(column, event)}
                    />
                  )}
                </div>
              );
            })}
          </div>

          {filteringFeature && state.isFilteringEnabled() && (
            <div
              className="filter-grid ui-grid-header"
              data-part="filters"
              ref={filterGridRef}
              style={{
                gridTemplateColumns,
                ['--ui-grid-header-sticky-top' as string]: `${headerStickyHeight}px`,
              }}
            >
              {visibleColumns.map((column) => {
                const pinned = state.isPinned(column);
                const pinOffset = pinned ? state.pinnedOffset(column) : null;
                return (
                  <label
                    key={column.name}
                    className={`filter-cell ui-grid-filter-container${pinned ? ' is-pinned' : ''}`}
                    data-part="filter-cell"
                    style={{
                      position: pinned ? 'sticky' : undefined,
                      left: pinOffset?.side === 'left' ? pinOffset.offset : undefined,
                      right: pinOffset?.side === 'right' ? pinOffset.offset : undefined,
                      zIndex: pinned ? 2 : undefined,
                    }}
                  >
                    <span className="sr-only ui-grid-sr-only">
                      {labels.filterColumn} {state.headerLabel(column)}
                    </span>
                    <input
                      className="ui-grid-filter-input"
                      type="text"
                      defaultValue={state.filterValue(column.name)}
                      placeholder={state.filterPlaceholder(column)}
                      disabled={state.isFilterInputDisabled(column)}
                      onChange={(e) => state.updateFilter(column.name, e.target.value)}
                    />
                  </label>
                );
              })}
            </div>
          )}

          {displayItems.length > 0 ? (
            virtualizationEnabled ? (
              <div className="grid-virtual-spacer" style={{ height: `${virtualScroll.totalHeight}px` }}>
                <div
                  className="body-grid ui-grid-canvas grid-virtual-body"
                  data-part="body"
                  role="rowgroup"
                  style={{
                    gridTemplateColumns,
                    position: 'absolute',
                    top: `${virtualScroll.offsetY}px`,
                    left: 0,
                  }}
                >
                  {itemsToRender.map(renderDisplayItem)}
                </div>
              </div>
            ) : (
              <div className="body-grid ui-grid-canvas" data-part="body" role="rowgroup" style={{ gridTemplateColumns }}>
                {displayItems.map(renderDisplayItem)}
              </div>
            )
          ) : (
            <div className="empty-state ui-grid-no-row-overlay" data-part="empty-state">
              <strong>{options.emptyMessage ?? labels.emptyHeading}</strong>
              <p>{labels.emptyDescription}</p>
            </div>
          )}
        </div>

        {paginationFeature && state.showPaginationControls() && (
          <footer
            className="pagination-bar ui-grid-pagination"
            data-part="pagination"
            role="navigation"
            aria-label={labels.paginationPage}
          >
            <p>{state.paginationSummary()}</p>
            <div className="pagination-controls">
              <button
                type="button"
                className="action action-secondary pagination-button"
                aria-label={labels.paginationPrevious}
                disabled={paginationCurrentPage <= 1}
                onClick={() => state.previousPage()}
              >
                <svg className="pagination-icon" viewBox="0 0 24 24" aria-hidden="true" focusable={false}>
                  <path d="M15.41 7.41L14 6l-6 6 6 6 1.41-1.41L10.83 12z" />
                </svg>
                <span className="sr-only">{labels.paginationPrevious}</span>
              </button>
              <span>
                {labels.paginationPage} {paginationCurrentPage} {labels.paginationOf} {paginationTotalPages}
              </span>
              <button
                type="button"
                className="action action-secondary pagination-button"
                aria-label={labels.paginationNext}
                disabled={paginationCurrentPage >= paginationTotalPages}
                onClick={() => state.nextPage()}
              >
                <svg className="pagination-icon" viewBox="0 0 24 24" aria-hidden="true" focusable={false}>
                  <path d="M8.59 16.59L10 18l6-6-6-6-1.41 1.41L13.17 12z" />
                </svg>
                <span className="sr-only">{labels.paginationNext}</span>
              </button>
              {state.pageSizeOptions().length > 0 && (
                <label className="pagination-size">
                  <span className="sr-only">{labels.paginationRows}</span>
                  <select
                    aria-label={labels.paginationRows}
                    value={paginationSelectedPageSize}
                    onChange={(e) => state.onPageSizeChange(e.target.value)}
                  >
                    {state.pageSizeOptions().map((size) => (
                      <option key={size} value={size}>
                        {size}
                      </option>
                    ))}
                  </select>
                </label>
              )}
            </div>
          </footer>
        )}
      </section>
    </div>
  );
}
